services:
  redis:
    image: redis
    container_name: redis
    networks:
      - net

  express_app:
    build: ./express_app
    container_name: express_app
    ports:
      - "3000:3000"
    depends_on:
      - redis
    networks:
      - net

networks:
  net:
    external: false
    name: net
